# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iChan' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iChan
  pod 'SDWebImage', '~> 5.6'
  pod 'SnapKit', '~> 5.0'
  pod 'ActiveLabel'
  pod 'Lightbox'

end
